### ISSUE TITLE
Use caching on travis?

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#100]
It's possible to cache abitrary directories on travis; https://docs.travis-ci.com/user/caching/#arbitrary-directories. Might be useful to cache the chianti database to save repeatedly hitting the download servers, and maybe even caching a full HDF5 database for the tests?

**Comment by wtbarnes** [comment]
Oh I was not aware of this! Yeah I will look into enabling that, at least for the downloads to begin with.

**Comment by wtbarnes** [comment]
Now moved off of Travis so I'm going to close this. If we still want to look into caching on GH actions (if this is even possible?) then I'm happy to reopen.
