### ISSUE TITLE
Add len() to Transitions

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#101]
It would be helpful if the `Transitions` class defined `__len__`, to get the number of transitions stored.

**Comment by wtbarnes** [comment]
Yes that would be great.

Similarly, I often find myself needing the number of energy levels for an ion. Since these are accessed through `__getitem__` on the `Ion` object itself, I wonder if the best way to do that would be to provide a `__len__` method on `Ion` too?
