### ISSUE TITLE
Support reading rrlvl files

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#114]
There is a new file format `.rrlvl` in v9, presumably related to the radiative recombination process in v9. We need a reader for this. I'm not entirely sure where this data is used yet.

**Comment by kdere** [comment]
the function is cireclvlRead in tools.io
you will see it mentioned in ion.setup()

**Comment by wtbarnes** [comment]
This report describes the structure of the files: http://www.chiantidatabase.org/tech_reports/24_rrlvl/chianti_report_24.pdf
