### ISSUE TITLE
Make fiasco/ion.py references consistent

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#152]
Currently in `fiasco/ion.py` there's two ways that refernces are referenced, using either a number e.g. `[1]` or a name e.g. `[young]`. We should choose a style and stick to it.

In addition, it might be worth consolidating all references to the bottom of the page, allowing individual docstrings to link to them as required to avoid duplicating reference info across multiple docstrings.

**Comment by wtbarnes** [comment]
I am +1 on moving all references to the bottom of the page. Having them repeated is annoying. I'm not sure how this would show up in the built docs? Would all of the references be in one docstring?
