### ISSUE TITLE
Use astropy configuration

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#16]
Currently, fiasco uses a simple configuration file and `configparser` to set some basic options for the package. Astropy has a [much more robust configuration system](http://docs.astropy.org/en/stable/config/) that fiasco should take advantage of. However, it seems there are issues when it comes to using it with affiliated packages](https://github.com/astropy/astropy/pull/5828). 

fiasco should aim to to take advantage of this configuration system once it is suitable for packages outside of astropy. Maybe it is already?

**Comment by Cadair** [comment]
You can use it, but your configs will go in the `~/.astropy` directory

**Comment by wtbarnes** [comment]
So something like 

```python
from astropy import config as _config

class Conf(_config.ConfigNamespace):
    setting_a = _config.ConfigItem(1,'a setting')
    setting_b = _config.ConfigItem('foo',another setting')

conf = Conf()
```

in `fiasco/__init__.py` should look in `~/.astropy/fiasco.cfg`?
