### ISSUE TITLE
Add repr for `IonCollection`

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#172]
This could include the number of ions in the collection, the temperature array, and the symbols of all ions in the collection (though this could be quite long for large collections of ions).

**Comment by devbazregari** [comment]
hi bro I hope you're doing great. bro, I'm a little bit confused about what you want. do you want me to set an __repr__ in your   
"IonCollection" class?

**Comment by wtbarnes** [comment]
Hello, apologies for the very delayed reply. Yes, if you'd like, please feel free to add a repr for the `IonCollection` class that shows some of the basic properties listed above. Feel free to reach out if you have any questions!
