### ISSUE TITLE
Add a GitHub Action to automate the release process

### ISSUE THREAD

**Issue by namurphy** [wtbarnes/fiasco#178]
There are a few GitHub Actions out there that automate the release process to PyPI.  For example, @StanczakDominik has been working on https://github.com/PlasmaPy/PlasmaPy/pull/1779, which I'm really excited about.  We could add a GitHub Action like that one to fiasco to facilitate quicker releases.

**Comment by StanczakDominik** [comment]
I'd be happy to help out with that here once we've had the opportunity to use the one at PlasmaPy a couple times and iron out the kinks :)

**Comment by wtbarnes** [comment]
We use a very minimal actions workflow to release the sunpy-soar package: https://github.com/sunpy/sunpy-soar/blob/main/.github/workflows/python-release.yml

My zeroth order plan was just to adapt this for fiasco.
