### ISSUE TITLE
Replace usage of `setup.py` and `setup.cfg` with `pyproject.toml`

### ISSUE THREAD

**Issue by namurphy** [wtbarnes/fiasco#189]
Adapted from https://github.com/PlasmaPy/PlasmaPy/issues/1680:

The Python community has been converging on using [`pyproject.toml`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/). The old way of doing it with `setup.py` and `setup.cfg` is [now considered legacy](https://pip.pypa.io/en/stable/reference/build-system/setup-py/).  The Python Packaging User Guide's tutorial on [packaging Python projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/) now includes `pyproject.toml` and doesn't include `setup.cfg` or `setup.py`.

We should move away from using our [`setup.cfg`](https://github.com/wtbarnes/fiasco/blob/main/setup.cfg) for configuration and packaging stuff when we have the option to, and instead use our [`pyproject.toml`](https://github.com/wtbarnes/fiasco/blob/main/pyproject.toml) file.  We should also drop our [`setup.py`](https://github.com/wtbarnes/fiasco/blob/main/setup.py`) and have `pyproject.toml` handle those responsibilities.

Some (or maybe all) of the configuration in `setup.cfg` for different tools would likely need to be moved to `pyproject.toml`, which would probably be best via multiple focused pull requests rather than one relatively large one.

**Comment by Cadair** [comment]
Note that not having a `setup.py` file present in the repo requires a (at the time of writing) very new version of pip to support development installs.

Having a two line `setup.py` file and moving everything else in to the other config files is what I would currently recommend.
