### ISSUE TITLE
Use changelog and render during releases

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#214]
For the first two releases, I've not used the changelog at all. Moving forward, a changelog should be required for any significant user-facing changes. These should then be rendered on each release using `towncrier`.

**Comment by Cadair** [comment]
May I suggest an alternative which is the github changelog approach now taken by reproject etc. Use the GitHub releases auto-changelog generator, and then use an action to edit the changelog file in the repo: https://github.com/astropy/reproject/blob/main/RELEASE_INSTRUCTIONS.md

**Comment by wtbarnes** [comment]
That sounds like a lot less effort so I'm in favor of it. 

When it comes to backports that are rendered as authored by the backport bot, do you know if there is a way to render those as the original PRs rather than the backport PRs?

**Comment by Cadair** [comment]
No I don't know. The packages I use this flow on tend to be very backport-light i.e. mostly don't do bugfixes off a branch.

**Comment by wtbarnes** [comment]
I've just been using the GH releases auto-changelog generator for the last couple of releases and I think that's more than sufficient for now so I'm going to close this.
