### ISSUE TITLE
Drop factor of 0.83 in contribution function

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#236]
The contribution function method currently includes a factor of $n_H/n_e\approx0.83$. This should be dropped as users may want to make different assumptions when it comes to what this ratio is. This means that the resulting EM is $n_Hn_e$ rather than $n_e^2$.

**Comment by wtbarnes** [comment]
The AIA response function example will need to be adjusted appropriately if this change as made as well as the documentation for the contribution function method to make sure that it is clear to users that this factor is not included.

**Comment by jwreep** [comment]
There should be a function similar to [proton_dens.pro](https://sohoftp.nascom.nasa.gov/solarsoft/packages/chianti/idl/utilities/proton_dens.pro) since this is also used in other locations.  The two-photon continuum method requires it, as well, for example.

**Comment by wtbarnes** [comment]
Alternatively, we could use `proton_to_electron_ratio`. The most important thing is that we are consistent anywhere this factor comes up. The three options then are:

1. Keep 0.83
2. Use the proton-electron ratio
3. Drop this factor entirely such that $EM\sim n_Hn_e$ rather than $n_e^2$
