### ISSUE TITLE
Add correction for ionization and recombination in level populations calculation 

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#24]
There should be a correction for ionization and recombination processes in the level population calculation. Currently, this is not included. See [section 2.3 of Landi et al. (2006)](http://adsabs.harvard.edu/abs/2006ApJS..162..261L) for more details as well as [section 6 of Dere et al. (2009)](http://adsabs.harvard.edu/abs/2009A%26A...498..915D).

**Comment by dstansby** [comment]
I've been taking a look at this, and am struggling a bit. I can read in the relevant files to get the level dependent recombination and ionziation rates (alphas below), and getting the abundances should be fine, but when it comes to 
<img width="367" alt="Screenshot 2021-02-26 at 19 30 46" src="https://user-images.githubusercontent.com/6197628/109346193-3cb00580-7869-11eb-9ec6-6a08d4cf9204.png">
I'm struggling to work out what the best way is to get the C_{g >i} rates. Presumably they're being calculated somewhere in `level_populations()`, but I'm not sure where. @wtbarnes any ideas?

**Comment by wtbarnes** [comment]
Sorry for taking a bit to get back to this. If I'm reading that expression correctly, the C_gi terms are the collisional excitation rate coefficients for the electrons which are available as a method on the `Ion` object: https://fiasco.readthedocs.io/en/latest/api/fiasco.Ion.html#fiasco.Ion.electron_collision_excitation_rate

**Comment by wtbarnes** [comment]
It may also be useful to have a look at this CHIANTI technical report: http://www.chiantidatabase.org/tech_reports/20_ionrec_lvl/chianti_report_20.pdf which also describes some of the differences introduced in v9.

**Comment by wtbarnes** [comment]
Also CHIANTI technical report No. 15: http://www.chiantidatabase.org/tech_reports/15_pops/chianti_report_15.pdf
