### ISSUE TITLE
Use additional Itoh files when computing free-free emission

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#248]
In v9.0.1 and above of the database, there are two additional files used for computing the free-free continuum: `itoh_integrated_gaunt.txt` and `itoh_integrated_gaunt_nonrel.txt`, as noted in [this mailing list post](https://groups.google.com/g/chianti/c/NWkq6BJkUWM). However, it is not clear to me excatly how these new files are used in the new free-free calculation or whether one of them replaces the non-relativistic Sutherland Gaunt factors.

**Comment by jwreep** [comment]
Both files are used in [ff_gaunt_itoh.pro](https://sohoftp.nascom.nasa.gov/solarsoft/packages/chianti/idl/continuum/ff_gaunt_itoh.pro), but I don't see what other routine calls this one.  

[ff_rad_loss.pro](https://sohoftp.nascom.nasa.gov/solarsoft/packages/chianti/idl/continuum/ff_rad_loss.pro) calls the Sutherland form, so perhaps this was meant to be included when relativistic forms are needed?  (High temperatures?)

Perhaps ask Peter?

**Comment by jwreep** [comment]
This is another form of the Gaunt factor corresponding to this function: 
https://github.com/wtbarnes/fiasco/blob/8ee514b71ab5a4fdff79ae6a1e65cef6a9256941/fiasco/ions.py#L1445

I still don't see if it's actually used by CHIANTI anywhere, but we could easily implement this form and make it an option to be used by the free-free radiative loss.
