### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/fiasco#267]
In #259, I dramatically changed the layout and format of the docs, including implementing a new them. However, there are still some rough edges when it comes to the format of the docs. As an example, there are places where it would be better to suppress one of the navigation sidebars or maybe change the formatting of some of the headings. 

Before the next major release, we should do a thorough review of the docs with an eye for formatting.

**Comment by jwreep** [comment]
Not sure when this happened, but the inheritance diagrams in the docs now appear to be broken.

**Comment by wtbarnes** [comment]
I think that's only broken on "stable". They appear to still be working on "latest": https://fiasco.readthedocs.io/en/latest/reference/code_ref/io.html#module-fiasco.io.sources. Once I do a release, this will all be fixed on stable as well.

**Comment by wtbarnes** [comment]
A lot of the outstanding issues I had in mind were handled in #286 so I'm going to close this.
