### ISSUE TITLE
f-f scaling with temperature?

### ISSUE THREAD

**Issue by jwreep** [wtbarnes/fiasco#284]
fiasco has free-free emission scaling as $\propto T^{-1/2}$:

https://github.com/wtbarnes/fiasco/blob/9ab2c61948b31691e6bece555a00c8e5f0fda071/fiasco/ions.py#L1316-L1317

Should this not be $\propto T^{+1/2}$?  The emission should generally increase with temperature (more collisions).  

ChiantiPy has this scaling: 
https://github.com/chianti-atomic/ChiantiPy/blob/89da3857bd1cf7491c3a269dd2d36ca21f269969/ChiantiPy/core/Continuum.py#L159

as does the IDL case:
`rad_loss[k]=rad_loss[k]+this_abund*this_ioneq[k]*factor*sqrt(t[k])*z^2*gaunt[k]`

The documents reference a book by Philips that I don't have access to, but the Itoh et al 2000 paper also suggests $T^{1/2}$:
<img width="436" alt="Screenshot 2024-05-15 at 3 55 17 PM" src="https://github.com/wtbarnes/fiasco/assets/33359703/4d64f0fb-bb5a-45a4-a8b7-f92e896f2d9c">

Could this be confirmed?  Has the equation been manipulated algebraically somehow? 

I see that #167 checked against the IDL code, so I'm very confused about this.

**Comment by wtbarnes** [comment]
I'm not sure exactly why these expressions are different, but I am extremely confident that the output of fiasco matches that of the IDL code: https://fiasco.readthedocs.io/en/latest/generated/gallery/idl_comparisons/continuum_comparison.html#sphx-glr-generated-gallery-idl-comparisons-continuum-comparison-py.

**Comment by wtbarnes** [comment]
Oh I know. It's because of the factor of $du$. You can rewrite it as $du=\hbar \mathrm{d}\omega / k_B T$. I've not checked but I assume with that extra factor of $\hbar/k_B$, the constant should work out to be the same as well.

**Comment by jwreep** [comment]
Aha!  That must be it.  Thank you!

I guess then I have to wonder about the physical interpretation.  It _should_ increase, no?  I was under the impression that the collision rate should increase, so there should be more emission.  Perhaps the actual cross-section decreases though?  Curious.

**Comment by jwreep** [comment]
For posterity's sake, the $T^{-1/2}$ scaling **is** correct for the intensity differential in wavelength, but the total radiative loss (integrated over wavelength) does in fact scale as $T^{1/2}$.  

The intensity equation 
$I_{ff}(T, \lambda) \propto \frac{1}{\lambda^{2} T^{1/2}} \exp{(\frac{-hc}{\lambda k T})}$
which integrated in wavelength space is
$R_{ff}(T) \propto T^{1/2} \exp{(\frac{-hc}{\lambda k T})}$.  

Much of my confusion stemmed from mixing up the two forms.
