### ISSUE TITLE
New numpy release (v2.0.0) causing issues?

### ISSUE THREAD

**Issue by jwreep** [wtbarnes/fiasco#289]
It seems like the newest release of Numpy (6/16/24) is causing issues with fiasco.  

For example, this line 
https://github.com/wtbarnes/fiasco/blob/f7e25600c0c511c58c707777391117451d4e9a63/fiasco/util/setup_db.py#L202
uses `np.string_` which has been [removed in this release](https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-python-api-removals).  This seems like it's causing the CI to fail (see the errors on #282 -- **every** single unit test is failing).

For the moment, perhaps pin the CI to an older version, but it seems like this might require a major overhaul to stamp out any issues.

**Comment by wtbarnes** [comment]
Thanks for bringing this up. I think the first step is to see whether the fixes that would accommodate v2.0 would also work with older versions.

To avoid problems like this in the future, we should probably also add an oldestdeps CI job as well as a devdeps one.
