### ISSUE TITLE
-- Building the files for elements not works first time with Spyder.

### ISSUE THREAD

**Issue by ktbug** [wtbarnes/fiasco#30]

**Comment by wtbarnes** [comment]
@ktbug I forgot exactly what this issue referred to. Could you clarify and include any relevant error messages?

**Comment by wtbarnes** [comment]
@ktbug I'm going to close this issue as I cannot remember what it refers to. If you can clarify and it is still a problem, feel free to reopen.

**Comment by ktbug** [comment]
Sadly,I am so busy that I can't remember.

I'll try to look back in my notes
