### ISSUE TITLE
Expected API change for PlasmaPy version 0.3.0

### ISSUE THREAD

**Issue by namurphy** [wtbarnes/fiasco#52]
As part of a reorganization of PlasmaPy subpackages, we decided to rename `plasmapy.atomic` to `plasmapy.particles`.  This change is in part because the subpackage includes data and representations for a bunch of different fundamental particles and should eventually include custom particles, so "atomic" wasn't broad enough.  Once we release version 0.3.0, I'll try to remember to submit a PR here to unbreak what we have broken.

Relevant PR: https://github.com/PlasmaPy/PlasmaPy/pull/742
Future package structure described here: https://github.com/PlasmaPy/PlasmaPy-PLEPs/pull/26

**Comment by wtbarnes** [comment]
Thanks for heads up! Now realizing how much I depend on `plasmapy.atomic` just for parsing inputs 😄

**Comment by wtbarnes** [comment]
This is finally causing all of the tests to fail 😅
