### ISSUE TITLE
Caching the test database

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/fiasco#74]
As far as I can tell, running the tests attemptes to download and build a smaller version of the database in a temporary folder. If it could detect an already-present installation and use that instead it would save having to do this every time local tests are run.

**Comment by wtbarnes** [comment]
I intentionally made this change recently. I wanted to make the setup for the database on the CI easier and to avoid the test results being dependent on the state of how the database is configured on a given machine.

Building the minimal HDF5 version of the database takes no time at all, but downloading the tarball of the ASCII files every time can be a bit annoying (and probably is not very respectful to the CHIANTI webpage). In my mind, this should still be the default behavior, but I wonder if there is a way to cache this with pytest? 

Another option would just be to check the rc file (as is done when instantiating an ion) and download it there, though it feels strange to put a test-dependent configuration option in the rc file.

**Comment by dstansby** [comment]
Caching the download seems like the sensible option, with a SHA to check it's the right file.

**Comment by wtbarnes** [comment]
I wonder if the new remote data manager in sunpy would work for this…

**Comment by wtbarnes** [comment]
@dstansby are you happy with #79 and #86 as a solution to this?

**Comment by dstansby** [comment]
Yep 👍
